# Generated by Django 5.0.14 on 2025-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField()),
                ('civilid', models.CharField(max_length=12)),
                ('fileupload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
